# Generated by Django 4.1.7 on 2023-04-06 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100)),
                ('query_text', models.TextField(null=True)),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True)),
                ('reg_user', models.CharField(max_length=100, null=True)),
                ('udt_dtm', models.DateTimeField(null=True)),
                ('udt_user', models.CharField(max_length=100, null=True)),
                ('last_used_dtm', models.DateTimeField(auto_now=True)),
                ('public_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_run', models.BooleanField(default=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.script')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
