# Generated by Django 4.1.7 on 2023-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='use_yn',
            field=models.BooleanField(default=True),
        ),
    ]
