# Generated by Django 4.1.7 on 2023-04-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_script_use_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='public_yn',
        ),
        migrations.RemoveField(
            model_name='scriptpermission',
            name='can_run',
        ),
    ]
