# Generated by Django 4.1.7 on 2023-04-11 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('query', '0003_remove_script_public_yn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScriptPermission',
            new_name='ScriptUser',
        ),
        migrations.AddField(
            model_name='script',
            name='script_users',
            field=models.ManyToManyField(related_name='shared_scripts', through='query.ScriptUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
